title: Supreme Court Judgements
remote_theme: opendocsg/opendoc-theme
repository: opendocsg/opendoc-supreme-court-judgements
plugins:
  - jekyll-seo-tag
  - jekyll-include-cache
section_order:
  - '[2018] SGCA 81.md'
  - '[2018] SGHC 268.md'
  - '[2018] SGHC 254.md'
  - '[2018] SGHC 261.md'
  - '[2018] SGCA 85.md'
  - '[2018] SGHC 266.md'
  - '[2018] SGCA 84.md'
  - '[2018] SGCA 83.md'
  - '[2018] SGHC 257.md'
  - '[2018] SGHC 262.md'
  - '[2018] SGHC 265.md'
  - '[2018] SGHC 258.md'
  - '[2018] SGCA 86.md'
  - '[2018] SGHC 260.md'
  - '[2018] SGHC 256.md'
  - '[2018] SGHC 259.md'
  - '[2018] SGHC 263.md'
  - '[2018] SGCA 82.md'
  - '[2018] SGCA 80.md'
  - '[2018] SGHC 255.md'
  - '[2018] SGHC 253.md'
  - '[2018] SGCA 79.md'
  - '[2018] SGHCR 17.md'
  - '[2018] SGCA 78.md'
  - '[2018] SGHC 250.md'
  - '[2018] SGHC 200.md'
  - '[2018] SGHC 252.md'
  - '[2018] SGHC 251.md'
  - '[2018] SGHC 249.md'
  - '[2018] SGHC 247.md'
  - '[2018] SGHC 248.md'
  - '[2018] SGHC 246.md'
  - '[2018] SGHCF 17.md'
  - '[2018] SGCA 63.md'
  - '[2018] SGCA 77.md'
  - '[2018] SGHCR 16.md'
  - '[2018] SGHCF 16.md'
  - '[2018] SGCA 76.md'
  - '[2018] SGHC 244.md'
  - '[2018] SGHC(I) 9.md'
  - '[2018] SGHC 227.md'
  - '[2018] SGHC 230.md'
  - '[2018] SGHC 228.md'
  - '[2018] SGCA 67.md'
  - '[2018] SGCA 69.md'
  - '[2018] SGHC 232.md'
  - '[2018] SGCA 68.md'
  - '[2018] SGCA 64.md'
  - '[2018] SGCA 66.md'
  - '[2018] SGHC 243.md'
  - '[2018] SGHC 229.md'
  - '[2018] SGHC 245.md'
  - '[2018] SGCA 65.md'
  - '[2018] SGHCR 15.md'
  - '[2018] SGHC 241.md'
  - '[2018] SGHC 242.md'
  - '[2018] SGHC 202.md'
  - '[2018] SGCA 75.md'
  - '[2018] SGHC 240.md'
  - '[2018] SGHC 239.md'
  - '[2018] SGCA 74.md'
  - '[2018] SGHC 238.md'
  - '[2018] SGHC 237.md'
  - '[2018] SGHCF 15.md'
  - '[2018] SGHC 236.md'
  - '[2018] SGHC 231.md'
  - '[2018] SGHC 235.md'
  - '[2018] SGCA 73.md'
  - '[2018] SGHCR 14.md'
  - '[2018] SGHC 234.md'
  - '[2018] SGCA 71.md'
  - '[2018] SGHC 233.md'
  - '[2018] SGCA 72.md'
  - '[2018] SGCA 70.md'
  - '[2018] SGHC 213.md'
  - '[2018] SGHC 226.md'
  - '[2018] SGHC 225.md'
  - '[2018] SGHC 224.md'
  - '[2018] SGHC 221.md'
  - '[2018] SGHC 217.md'
  - '[2018] SGHC 223.md'
  - '[2018] SGHC 222.md'
  - '[2018] SGCA(I) 7.md'
  - '[2018] SGHC 220.md'
  - '[2018] SGHC 218.md'
  - '[2018] SGHC 214.md'
  - '[2018] SGHC 219.md'
  - '[2018] SGHC 131.md'
  - '[2018] SGHC 215.md'
  - '[2018] SGCA 60.md'
  - '[2018] SGCA 59.md'
  - '[2018] SGCA 61.md'
  - '[2018] SGHCF 13.md'
  - '[2018] SGCA 62.md'
  - '[2018] SGCA 58.md'
  - '[2018] SGHC 216.md'
  - '[2018] SGHC 211.md'
  - '[2018] SGHC 210.md'
  - '[2018] SGHC 130.md'
  - '[2018] SGHC 212.md'
  - '[2018] SGHC 193.md'
  - '[2018] SGHC 209.md'
  - '[2018] SGHC 208.md'
  - '[2018] SGHC 206.md'
  - '[2018] SGHC 205.md'
  - '[2018] SGHC 207.md'
  - '[2018] SGHC 198.md'
  - '[2018] SGHC 203.md'
  - '[2018] SGHC 192.md'
  - '[2018] SGHC 204.md'
  - '[2018] SGHC 199.md'
  - '[2018] SGHC 201.md'
  - README.md
baseurl: /opendoc-supreme-court-judgements
server_PROD: 'https://search.opendoc.sg'
server_DEV: 'https://search-staging.opendoc.sg'
styling_options:
  primary_brand_color: '#8B4513'
  logo_path: /assets/logo.png
  opendoc_logo_path: /assets/images/logo-full.png
